Fix errors in README.md
AutoReviser/AutoReviser pull request #5
Opened 2018-07-16 06:35 UTC by suhyeon

Fix error in README.md. README.md was have error that the parameter
'source' did not have a type at Example Code. So, added a type of
parameter to fix Issues.

This resolves #4

2018-07-16 11:07 UTC, gyuwon requested changes

2018-07-16 11:07 UTC, gyuwon commented on README.md
> +    public static ImmutableObject WithAlfa(this ImmutableObject source, int alfa)
이 줄은 80자를 넘기니 `this` 앞에서 줄바꿈 부탁드립니다.

2018-07-16 11:07 UTC, gyuwon commented on README.md
> +    public static ImmutableObject WithBravo(this ImmutableObject source, string bravo)
이 줄은 80자를 넘기니 `this` 앞에서 줄바꿈 부탁드립니다.

2018-07-16 11:07 UTC, gyuwon commented on README.md
> +    public static ComplexImmutableObject WithCharlie(this ComplexImmutableObject source, int charlie)
이 줄은 80자를 넘기니 `this` 앞에서 줄바꿈 부탁드립니다.

2018-07-17 03:51 UTC, suhyeon commented on README.md
> +    public static ImmutableObject WithAlfa(this ImmutableObject source, int alfa)
변경했습니다! 확인부탁드립니다!

2018-07-17 03:51 UTC, suhyeon commented on README.md
> +    public static ImmutableObject WithBravo(this ImmutableObject source, string bravo)
변경했습니다! 확인부탁드립니다!

2018-07-17 03:51 UTC, suhyeon commented on README.md
> +    public static ComplexImmutableObject WithCharlie(this ComplexImmutableObject source, int charlie)
변경했습니다! 확인부탁드립니다!

2018-07-18 04:56 UTC, gyuwon approved these changes

2018-07-18 04:58 UTC, merged